---
title: "DanishDataset"
output: pdf_document
date: "2024-12-09"
---

```{r }
library(evir)
library(fitdistrplus)

times <- attr(danish, "times")
df_data <- data.frame(Times = times, ClaimsAmount= danish)
times_intervals = as.numeric(diff(df_data$Times), units="days")

head(df_data)
```


```{r}
# Ajuster une loi exponentielle aux données pour voir si les écarts inter-temps suivent une loi exponentielle

fit <- fitdist(times_intervals, "exp")

# Comparaison visuelle : histogramme vs distribution ajustée
hist(times_intervals, probability = TRUE, breaks = 30, 
     main = "Intervalles vs Distribution Exponentielle", 
     xlab = "Intervalles (jours)", col = "skyblue", border = "white")
curve(dexp(x, rate = fit$estimate), col = "red", lwd = 2, add = TRUE)
legend("topright", legend = c("Données", "Exponentielle ajustée"), col = c("skyblue", "red"), lwd = 2)

```



```{r}
# Autocorrélation des intervalles pour l'indépendance des intervalles de temps
acf(times_intervals, main = "Autocorrélation des intervalles")
```

```{r}
#Cleaning
df_data <- df_data[!duplicated(df_data[, c("Times")]), ]
new_times_intervals = as.numeric(diff(df_data$Times), units="days")
```

```{r}
#Variable declarations
T_list = cumsum(new_times_intervals)
Tmax = max(T_list)
n = length(df_data$ClaimsAmount)
```

```{r}
#Test de Laplace
L = sum(T_list) / Tmax
Zobs = sqrt(12/n) * (L-n/2)

p_val = 1-pnorm(Zobs)

print(p_val)
#On obtient une p_valeur inférieure à 0.05. Ainsi, nous sommes face à un processus de Poisson inhomogène.
```
```{r}
#Test de Boswell

```





