---
title: "R Notebook"
output: html_notebook
---

```{r simulPPh,eval=FALSE}
simulPPh <- function(Tmax, n) {
  return(sort(runif(n, 0, Tmax)))
}

simulPPi <- function(lambda_fct,lambda_fct_inv,Tmax,n)
{
  u = sort(runif(n, 0, lambda_fct(Tmax)))
  u = lambda_fct_inv(u)
  return(u)
}
```


```{r plot.PP}
plot.PP<- function(PP)
{
  # plot the counting process (with jumps of size 1 (starting at point (0,0))):
  plot(c(0,PP),0:length(PP),type="s",xlab="time t",ylab="number of events by time t")
  # add the arrival times on the horizontal axis: 
  points(PP,0*PP,type="p",pch=16)
  # link arrival times with the counts:
  lines(PP,0:(length(PP)-1),type="h",lty=2)
}
```


```{r}
lambda_t <- function(t){return(exp(t))}
lambda_t_inv <- function(t){return(log(t))}
l = simulPPi(lambda_t, lambda_t_inv, Tmax=1.0, n=10)
plot.PP(l)
l
```



```{r}
lambda_t <- function(t){return(exp(t)-1)}
lambda_t_inv <- function(t){return(log(t+1))}
Tmax = 4.0
n_list = 10


z_alpha = qnorm(1 - 0.05)

count=0
count2=0

for (k in 1:5000){
  PPi = simulPPi(lambda_t, lambda_t_inv, Tmax, n_list)
  L = sum(PPi) / Tmax
  Zobs = sqrt(12/n_list) * (L - n_list/2)
  
  p_val = 1-pnorm(Zobs)
  
  if (p_val <= 0.05)
    count2 = count2 + 1
  
  if (Zobs >= z_alpha)
    count = count + 1
}

print(count / 5000)
print(count2 / 5000)
```




